### PR TITLE
Implement Help page

### PR DESCRIPTION
**Pull request by alexa-nov**
Converted the mockup of the help page design to code. Includes the Help page and css styling. Also linked the help page in the router in App.js.

### CODE REVIEW

**Comment by cchun01** [comment]
All looks good to me!

**Comment by alexa-nov** [comment]
Thanks for taking a look Colin!

**Comment by rizenson** [comment]
Looks good! Thanks!

**Comment by alexa-nov** [comment]
Thanks Rachel!

**Comment by jupentudge** [comment]
Looks good! It was a very clean implantation of the Help page design.

**Pull request merged**
