### PR TITLE
Connect Notes to pull data from backend

### PR DESCRIPTION
**Pull request by rizenson**

### CODE REVIEW

**Comment by alexa-nov** [comment]
Changes made to the New Note file looks like it keeps all the front-end intact. Nice job.
With the REST API implementation of being able to delete, we should look into adding this feature for users. Probably make a new issue for it so that the frontend can match the backend with this implementation.

**Comment by cchun01** [comment]
Thank you so much, this change looks great! Now that we have the backend working, I can work on checking the login information of users.

**Comment by rizenson** [comment]
> Changes made to the New Note file looks like it keeps all the front-end intact. Nice job. With the REST API implementation of being able to delete, we should look into adding this feature for users. Probably make a new issue for it so that the frontend can match the backend with this implementation.

Yeah i was thinking of adding a button to delete a note which shouldn't be too bad I just wanted to run the UI past you guys before I implemented it

**Comment by rizenson** [comment]
> Thank you so much, this change looks great! Now that we have the backend working, I can work on checking the login information of users.

Yeah for checking the login page credentials it should be a combination of the checking we did in the sign up page and the grabbing from the data base like we did on this PR.

**Pull request merged**
