### PR TITLE
Log in2

### PR DESCRIPTION
**Pull request by cchun01**
Made edits to provided parameters on click on the sign in page.

### CODE REVIEW

**Comment by alexa-nov** [comment]
No comments. All changes look good to me.

**Comment by cchun01** [comment]
Thank you!

**Comment by rizenson** [comment]
We will have to validate the email with backend but for now it looks good!

**Comment by cchun01** [comment]
> We will have to validate the email with backend but for now it looks good!

Thank you!

**Comment by jupentudge** [comment]
Wanted to mention implantation looks good, thank you for taking into account my changes as well since we were both working on the login page. Clean implantation!

**Pull request merged**
